services:
  clients:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rho_clients
    volumes:
      - ./rho_clients/generated:/app/rho_clients/generated:rw
    network_mode: host

    command: tail -f /dev/null